services:
  - type: web
    name: oraculix-backend
    env: node
    plan: free
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
