services:
  - type: web
    name: oraculix-backend
    env: node
    plan: free
    buildCommand: |
      npm install --prefix backend
      cd frontend && npm install && npm run build
    startCommand: node backend/server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
