services:
  - type: web
    name: oraculix-backend
    env: node
    plan: free
    buildCommand: |
      cd backend && npm install         # Instala dependencias backend (incluye dotenv)
      cd ../frontend && npm install     # Instala dependencias frontend
      npm run build --prefix ../frontend # Compila frontend
    startCommand: node server.js
    workingDirectory: backend # Ejecuta todo desde /backend
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
#nuevo intento
